<a href="https://colab.research.google.com/github/u1353279/Feature-Selection/blob/master/Linear_and_Logistic_L1%2CL2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest,SelectPercentile
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.feature_selection import SelectFromModel

In [4]:
df=pd.read_csv('/content/drive/My Drive/santandar.csv/train.csv',nrows=20000)

In [5]:
X=df.drop('TARGET',axis=1)
y=df['TARGET']

In [6]:
X.shape,y.shape

((20000, 370), (20000,))

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=43)

Esitimation of coefficients of linear regression (higher the coeffcient more relevent it is).
as there is no gradient in linear we dont need regularisation

In [8]:
sel=SelectFromModel(LinearRegression())

In [9]:
sel.fit(X_train,y_train)

SelectFromModel(estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                           n_jobs=None, normalize=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [10]:
sel.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [11]:
sel.estimator_.coef_

array([ 1.09921109e-07,  7.44109843e-08,  2.10185945e-03, -3.78580228e-07,
       -3.51370719e-05, -7.76352430e-06, -1.37898302e-04,  1.66216591e-05,
        6.19691668e-05, -1.60769450e-04, -1.01913756e-05,  1.03567487e-04,
       -2.44310589e-05, -1.05565572e-05,  7.90780405e-05, -6.69271283e-06,
        5.22355725e-05, -8.16853812e-05, -1.67785574e-05, -4.86932766e-07,
        7.83345261e-03, -1.25080743e-03,  6.67647636e-08, -7.07661251e-08,
       -5.94263224e-02,  2.62379830e-02, -3.42373415e-03, -2.78631621e-08,
        1.16250286e-03,  5.92041256e-03, -9.66686101e-02,  1.14085662e-01,
        4.25008448e-03, -9.55420431e-03, -4.40936277e-03,  9.63416364e-03,
       -5.90810441e-02, -2.77605476e-11,  6.28943847e-12, -5.94870034e-02,
       -1.12635532e-02, -1.39484753e-02, -2.19183196e-02, -9.35942963e-03,
       -6.94755709e-12,  6.52676505e-12, -2.03807202e-02, -2.30380190e-03,
        2.65931250e-03, -1.50493495e-02, -2.00488104e-02, -1.30914730e-01,
       -2.35396660e-02,  

In [12]:
np.mean(abs(sel.estimator_.coef_))

0.022717628641280123

In [13]:
# the features that are greater than the mean are only selected

In [14]:
features=X_train.columns[sel.get_support()]
features

Index(['ind_var5_0', 'ind_var5', 'ind_var12_0', 'ind_var12', 'ind_var13_largo',
       'ind_var13', 'ind_var25_cte', 'ind_var26_0', 'ind_var26_cte',
       'ind_var26', 'ind_var25_0', 'ind_var25', 'ind_var30_0', 'ind_var30',
       'ind_var31_0', 'ind_var31', 'ind_var32_cte', 'ind_var32_0', 'ind_var32',
       'ind_var33_0', 'ind_var37_cte', 'ind_var39_0', 'ind_var41_0',
       'num_var1_0', 'num_var31_0', 'num_var31', 'num_var33_0', 'num_var40_0',
       'num_var42', 'num_var44_0', 'num_var44', 'delta_imp_compra_var44_1y3',
       'delta_num_compra_var44_1y3', 'ind_var10_ult1', 'ind_var10cte_ult1',
       'ind_var9_cte_ult1', 'ind_var9_ult1', 'num_aport_var17_hace3',
       'num_compra_var44_hace3', 'num_meses_var44_ult3',
       'num_op_var40_efect_ult1', 'num_op_var40_efect_ult3',
       'num_op_var41_efect_ult1', 'num_op_var41_efect_ult3',
       'num_op_var39_efect_ult1', 'num_op_var39_efect_ult3'],
      dtype='object')

In [15]:
len(features)

46

In [16]:
# lets get the transformed features only

In [17]:
X_train_reg=sel.transform(X_train)
X_test_reg=sel.transform(X_test)

In [18]:
X_train_reg.shape

(14000, 46)

In [19]:
# we have reduced down to 46 features

In [20]:
def run_random_forest(X_train,X_test,y_train,y_test):
  clf=RandomForestClassifier(n_estimators=100,random_state=0)
  clf.fit(X_train,y_train)
  y_pred=clf.predict(X_test)
  print('AccUracy on test set: ')
  print(accuracy_score(y_test,y_pred))

Original dataset performance

In [21]:
%%time
run_random_forest(X_train,X_test,y_train,y_test)

AccUracy on test set: 
0.9581666666666667
CPU times: user 3.74 s, sys: 7.58 ms, total: 3.75 s
Wall time: 3.76 s


In [22]:
#after feature selection

In [23]:
%%time
run_random_forest(X_train_reg,X_test_reg,y_train,y_test)

AccUracy on test set: 
0.9591666666666666
CPU times: user 811 ms, sys: 76 µs, total: 811 ms
Wall time: 812 ms


We can see an imporovment in both accuracy and training time

L1 regularisation

In [24]:
sel=SelectFromModel(LogisticRegression(penalty='l1',C=10,solver='liblinear'))
sel.fit(X_train,y_train)
sel.get_support()

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False, False, False, False,  True,  True, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False, False, False,  True,  True,  True, False,  True,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False, False,

In [25]:
sel.estimator_.coef_

array([[ 3.38490106e-06,  9.42726374e-06,  3.83492473e-02,
        -6.84225696e-05,  6.06852214e-04, -5.24486574e-04,
        -4.92608562e-03,  1.60178069e-03,  9.61814807e-03,
        -1.25754171e-02,  6.29672003e-04,  9.11571009e-04,
        -5.96461371e-04,  2.39276030e-04, -1.10180990e-04,
        -4.40371192e-05,  3.17673874e-04,  9.24586206e-06,
        -1.35116767e-04, -2.61072544e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.39490668e+00, -2.32721838e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.36986724e+00,  2.36174733e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.56467577e-01,  0.00000000e+00,
         0.00000000e+00,  6.62096364e-01,  0.00000000e+0

In [26]:
l1_features=X_train.columns[sel.get_support()]
l1_features

Index(['var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3', 'imp_op_var40_ult1',
       'imp_op_var41_comer_ult1',
       ...
       'saldo_medio_var8_ult3', 'saldo_medio_var12_hace3',
       'saldo_medio_var12_ult1', 'saldo_medio_var12_ult3',
       'saldo_medio_var13_corto_hace2', 'saldo_medio_var13_corto_hace3',
       'saldo_medio_var13_corto_ult1', 'saldo_medio_var13_corto_ult3',
       'saldo_medio_var13_largo_hace2', 'saldo_medio_var13_medio_ult1'],
      dtype='object', length=138)

In [27]:
len(l1_features)

138

In [28]:
X_train_l1=sel.transform(X_train)
X_test_l1=sel.transform(X_test)

In [29]:
%%time
run_random_forest(X_train_l1,X_test_l1,y_train,y_test)

AccUracy on test set: 
0.9556666666666667
CPU times: user 2.51 s, sys: 4.99 ms, total: 2.51 s
Wall time: 2.52 s


In [30]:
# orginal

In [31]:
%%time
run_random_forest(X_train,X_test,y_train,y_test)

AccUracy on test set: 
0.9581666666666667
CPU times: user 3.72 s, sys: 5.98 ms, total: 3.73 s
Wall time: 3.74 s


L2 Regularisation

In [32]:
sel=SelectFromModel(LogisticRegression(penalty='l2',C=0.05,solver='liblinear'))
sel.fit(X_train,y_train)
sel.get_support()

array([ True,  True, False,  True, False,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [33]:
sel.estimator_.coef_

array([[-4.31596103e-05,  3.82952718e-06, -1.91490205e-07,
        -1.07366065e-06,  5.66382951e-08, -1.10679518e-06,
         9.41575858e-08, -1.34236824e-08,  1.93697003e-07,
         3.27519044e-07,  2.15375451e-07, -3.75192907e-08,
        -1.09337150e-06,  3.31746537e-06,  4.19832049e-06,
         3.41567503e-06,  3.51116237e-06,  4.52583953e-06,
         3.63105048e-06, -1.18083030e-07,  3.61899567e-10,
         2.54417107e-10,  0.00000000e+00,  0.00000000e+00,
        -1.59483090e-08, -2.24150647e-08, -1.75675384e-11,
        -1.11059613e-11,  1.11665982e-09,  7.77787457e-10,
        -6.46597366e-10, -3.64067345e-10, -3.05818023e-10,
        -2.09760601e-10, -2.62159169e-10, -9.64226916e-11,
        -9.13649708e-11, -2.68410135e-12, -2.68410135e-12,
        -3.53182248e-10, -1.16839565e-10, -4.56340559e-11,
        -4.40566366e-11, -3.30095987e-11,  0.00000000e+00,
         0.00000000e+00,  9.12327227e-11, -9.81898571e-11,
        -6.72997543e-11, -3.26594983e-10, -2.56319710e-1

In [34]:
l2_features=X_train.columns[sel.get_support()]
l2_features

Index(['ID', 'var3', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult3',
       'imp_op_var41_comer_ult3', 'imp_op_var41_efect_ult1',
       'imp_op_var41_efect_ult3', 'imp_op_var41_ult1',
       'imp_op_var39_efect_ult1', 'imp_op_var39_efect_ult3',
       'imp_op_var39_ult1', 'saldo_var5', 'saldo_var12', 'saldo_var13_corto',
       'saldo_var13_largo', 'saldo_var13', 'saldo_var14', 'saldo_var17',
       'saldo_var24', 'saldo_var26', 'saldo_var25', 'saldo_var30',
       'saldo_var31', 'saldo_var42', 'imp_aport_var13_hace3',
       'imp_aport_var13_ult1', 'imp_var43_emit_ult1', 'imp_trans_var37_ult1',
       'saldo_medio_var5_hace2', 'saldo_medio_var5_hace3',
       'saldo_medio_var5_ult1', 'saldo_medio_var5_ult3',
       'saldo_medio_var8_hace2', 'saldo_medio_var12_hace3',
       'saldo_medio_var12_ult1', 'saldo_medio_var12_ult3',
       'saldo_medio_var13_corto_hace2', 'saldo_medio_var13_corto_ult1',
       'saldo_medio_var13_corto_ult3', 'saldo_medio_var13_largo_hace2',
       'saldo_me

In [35]:
len(l2_features)

43

In [36]:
X_train_l2=sel.transform(X_train)
X_test_l2=sel.transform(X_test)

In [37]:
%%time
run_random_forest(X_train_l2,X_test_l2,y_train,y_test)

AccUracy on test set: 
0.9553333333333334
CPU times: user 2.51 s, sys: 992 µs, total: 2.51 s
Wall time: 2.52 s
